services:
  - type: web
    name: ecommerce-analytics
    env: python
    buildCommand: pip install -r requirements.txt && python 01_data_generation.py && python 02_data_cleaning.py
    startCommand: python 04_dashboard.py